### ISSUE TITLE
I am confused by the given example

### ISSUE THREAD

**Issue by szl0072** [InsightDataScience/donation-analytics#1]
In the sixth and seven record of the example, the names are different but somehow the ids and zip codes are the same for both of them. Are these typos? Or will we expect something like this in the test cases?

They are very confusing for me. If you could clarify a lit bit, that would be great.

**Comment by emhoa** [comment]
Hi there @szl0072 , I'd recommend you re-read the Readme. And yes, you could expect similar input in our testing. Finally, the Readme also asks that you email us questions rather than post issues. Thank you

**Comment by szl0072** [comment]
Thanks @emhoa. And sorry for the inconvenience.
